### ISSUE TITLE
Add hydrophone period parameter

### ISSUE THREAD

**Issue by ryan-summers** [PalouseRobosub/robosub_simulator#20]
Currently, the hydrophone time deltas are published every cycle that gazebo sends out position messages. However, this is not the real situation. In reality, hydrophone pings only occur once every two seconds.
Conversely, high rates are desirable for debugging systems to ensure that things are working properly. For this reason, add in a parameter for the rate at which hydrophones will ping. This will then be loaded by the simulator bridge so that it only sends out a time delta message at that rate using the throttled publisher class.

**Comment by bkallaher** [comment]
Use the ThrottledPublisher class.

**Comment by dcrossman** [comment]
Is there any documentation for the ThrottledPublisher class @bkallaher ? Because I can't find a thing...

**Comment by skallaher** [comment]
The ThrottledPublisher is a class I made at James's request. It should be under src/utility.

**Comment by irwineffect** [comment]
Hmm...to properly use the ThrottledPublisher class, it looks like we need to tweak our settings so that our robosub package is properly exported, then have the simulator require the package. Some relevant links:

http://answers.ros.org/question/201977/include-header-file-from-another-package-indigo/
http://docs.ros.org/indigo/api/catkin/html/howto/format2/building_libraries.html

**Comment by dcrossman** [comment]
Fixed by #52
