### ISSUE TITLE
Cobalt control system simulation PID parameters are not used

### ISSUE THREAD

**Issue by ryan-summers** [PalouseRobosub/robosub_simulator#91]
It appears that the simulator is actually not using the cobalt_sim.yaml parameters for the control system. To verify this, launch the simulator normally and test behavior (this should behave normally).
Next, change the control system node launch to use robosub delayed_node.sh to ensure that cobalt_sim.yaml parameters are loaded. (the submarine should misbehave).

**Comment by bkallaher** [comment]
From the roslaunch page:

roslaunch evaluates the XML file in a single pass. Includes are processed in depth-first traversal order. Tags are evaluated serially and the last setting wins. Thus, if there are multiple settings of a parameter, the last value specified for the parameter will be used.

Therefore param tags are guaranteed to be evaluated in order. The issue is not with the simulator but with your new launch system.
