### ISSUE TITLE
Gate task unit test

### ISSUE THREAD

**Issue by Sindorman** [PalouseRobosub/robosub_simulator#99]
Implement a way for either simulator to detect when sub passed the gate or make a unit test implicitly detect it based on it's location/position.

**Comment by skallaher** [comment]
This issue belongs in the Robosub repo.

**Comment by Sindorman** [comment]
@skallaher I haven't researched it yet, but I expect it to involve changes in simulator. For example a script that reads/detects position of sub in simulator, and checks it relative to the box of exit side of gate.

**Comment by skallaher** [comment]
The test itself can listen to the output from Gazebo and get the position of any and all models in the environment. This includes the gate and submarine. There should be no need to make changes to the simulator.

**Comment by Sindorman** [comment]
But it will be probably needs to be placed in robosub_simulator repository, because it will not run on the sub itself?

**Comment by skallaher** [comment]
There isn't a clear cut answer to this. Having the tests in the robosub repo also makes sure that they are available to run when the build server is run. In addition, this keeps the tests near the source they are testing. From what I can tell, unless @irwineffect knows otherwise, this is merely a design decision.
